#!/usr/bin/env bash
# this script installs Nginx to listen on port 80
# and when querying with get return html content

sudo apt-get update -y

sudo apt-get install nginx -y

echo 'Hello World!' > /var/www/html/index.html

NEW_RULE="\\\n\tlocation = /redirect_me {\n\t\t return 301 https://www.youtube.com/channel/UCm6pFvqgfVikJ0tLIINePxg?app=desktop&fbclid=PAAaYebExjroPc-CPMJexhPUplo6fISfKSRG-9JcIlJ7IZwA_2e0C9DWB2tAs: \n\t}\n"

sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.spare

sudo sed -i "53i $NEW_RULE" /etc/nginx/sites-available/default 

sudo service nginx restart
