#!/usr/bin/env bash
# this script installs Nginx to listen on port 80
# and when querying with get return html content

sudo apt-get update -y

sudo apt-get install nginx -y

echo 'Hello World!' > /var/www/html/index.html
echo 'Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null'

NEW_RULE="\\\n\tlocation = /redirect_me {\n\t\t return 301 https://www.youtube.com/channel/UCm6pFvqgfVikJ0tLIINePxg?app=desktop&fbclid=PAAaYebExjroPc-CPMJexhPUplo6fISfKSRG-9JcIlJ7IZwA_2e0C9DWB2tAs: \n\t}\n"

sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.spare

sudo sed -i "53i $NEW_RULE" /etc/nginx/sites-available/default

NEW_RULE="\\\n\terror_page 404 /404.html;\n\n\tlocation = /404.html {\n\t\tinternal;\n\t}\n"

sudo sed -i "53i $NEW_RULE" /etc/nginx/sites-available/default
sudo service nginx restart
