#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend Tolu.Olanrewaju
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 435753-web-01 100.26.231.68
        server 435753-web-02 54.173.140.10
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
